######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Domino
#  (C) Copyright HCL Technologies Limited 1996, 2023
######################################################

# Default values used by the domino-shared helm chart.

image:
  imageCredentials:
    # -- Hostname of a private container registry
    registry: registry.example.com
    # -- Username for a private container registry
    username: registry_user
    # -- Password for a private container registry
    password: registry_password

ingress:
  # -- Ingress class. Must be included in "kubectl get ingressclass".
  class: nginx

certManager:
  # -- Should ClusterIssuer resource for Let's Encrypt be crearted?
  createIssuer: true
  # -- Type of Let's Encrypt certificate authority ("staging" or "prod")
  leCertificate: staging
  # -- Email used when creating a profile for Let's Encrypt
  leEmail: name@example.com