apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: {{ now | date "2006-01-02T15:04:05Z07:00" }}
  name: {{ .Release.Name }}-ids
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}

data:
{{- if .Values.install.mountIds }}

  {{ if and .Values.domino.org.useExistingCertifierID .Values.files.certID -}}
  {{ .Values.domino.org.idFileName }}: {{ .Values.files.certID | b64enc }}
  {{- end }}

  {{ if and .Values.domino.server.useExistingServerID .Values.files.serverID -}}
  {{ .Values.domino.server.idFileName }}: {{ .Values.files.serverID | b64enc }}
  {{- end }}

  {{ if and .Values.domino.admin.useExistingAdminID .Values.files.adminID -}}
  {{ .Values.domino.admin.idFileName }}: {{ .Values.files.adminID | b64enc }}
  {{- end }}

{{- end }}