{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "domino.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: hcl-domino
    server: {{ .Values.domino.server.name | lower }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}    
    {{- end }}
{{- end }}