apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}